networks:
  traefik_bridge:
    external: true

services:
  adguard:
    container_name: adguard
    image: adguard/adguardhome:latest
    ports:
      - 53:53/tcp
      - 53:53/udp
    networks:
      - traefik_bridge
    env_file:
      - stack.env
    volumes:
      - /mnt/storage-pool/apps/adguard/data:/opt/adguardhome/work
      - /mnt/storage-pool/apps/adguard/config:/opt/adguardhome/conf
    labels:
      - traefik.enable=true
      - traefik.http.routers.adguard.rule=Host(`dns.starsystem.dev`)
      - traefik.http.routers.adguard.middlewares=vpn-only@docker
      - traefik.http.services.adguard.loadbalancer.server.port=3000
    restart: always