networks:
  traefik_bridge:
    external: true

services:
  drone:
    container_name: drone
    image: drone/drone:2
    environment:
      DRONE_GITEA_CLIENT_ID: ${DRONE_GITEA_CLIENT_ID}
      DRONE_GITEA_CLIENT_SECRET: ${DRONE_GITEA_CLIENT_SECRET}
      DRONE_GITEA_SERVER: https://git.starsystem.dev
      DRONE_GIT_ALWAYS_AUTH: true
      DRONE_RPC_SECRET: ${DRONE_RPC_SECRET}
      DRONE_SERVER_HOST: ci.starsystem.dev
      DRONE_SERVER_PROTO: https
      DRONE_DATABASE_DRIVER: postgres
      DRONE_DATABASE_DATASOURCE: ${DRONE_DATABASE_DATASOURCE}
      DRONE_DATABASE_SECRET: ${DRONE_DATABASE_SECRET}
    networks:
      - traefik_bridge
    volumes:
      - /mnt/storage-pool/apps/drone:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.gitea.rule=Host(`ci.starsystem.dev`)
      - traefik.http.services.gitea.loadbalancer.server.port=80
    restart: always

  postgres:
    container_name: drone-postgres
    image: postgres:17
    env_file:
      - stack.env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - /mnt/storage-pool/databases/postgresql/drone:/var/lib/postgresql/data
    labels:
      - traefik.enable=false
    restart: always