networks:
  default:
    name: gitea_internal

  traefik_bridge:
    external: true

services:
  gitea:
    container_name: gitea
    image: docker.io/gitea/gitea:latest
    networks:
      - default
      - traefik_bridge
    depends_on:
      - postgres
    ports:
      - "2222:2222"
    healthcheck:
      test: curl -fSs http://localhost:3000/api/healthz || exit 1
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 10s
    environment:
      USER: apps
      GITEA_APP_NAME: Gitea | Constellation
      GITEA__database__DB_TYPE: postgres
      GITEA__database__HOST: postgres:5432
      GITEA__database__NAME: ${DB_DATABASE}
      GITEA__database__USER: ${DB_USERNAME}
      GITEA__database__PASSWD: ${DB_PASSWORD}
      GITEA__mailer__ENABLED: "true"
      GITEA__mailer__FROM: ${EMAIL_FROM}
      GITEA__mailer__PROTOCOL: smtp
      GITEA__mailer__SMTP_ADDR: ${EMAIL_HOST}
      GITEA__mailer__SMTP_PORT: ${EMAIL_PORT}
      GITEA__mailer__USER: ${EMAIL_USERNAME}
      GITEA__mailer__PASSWD: ${EMAIL_PASSWORD}
      GITEA__security__SECRET_KEY: ${SECRET_KEY}
      GITEA__security__INTERNAL_TOKEN: ${INTERNAL_TOKEN}
      GITEA__security__INSTALL_LOCK: "true" # Disables the install screen
      GITEA__server__DOMAIN: git.starsystem.dev
      GITEA__server__SSH_LISTEN_PORT: "2222"
      GITEA__server__SSH_DOMAIN: git.starsystem.dev
      GITEA__server__SSH_PORT: "22"
      GITEA__server__ROOT_URL: https://git.starsystem.dev/
      GITEA__server__START_SSH_SERVER: "true"
      GITEA__server__PROTOCOL: http
      GITEA__server__SSH_AUTHORIZED_KEYS_BACKUP: "true"
      GITEA__service__DISABLE_REGISTRATION: "true" # Prevent users from registering themselves
      GITEA__admin__USER_EXTERNAL_USER_DISABLE_FEATURES: deletion # Users cannot delete their Gitea account (this will be done via LDAP instead)
    volumes:
      - /mnt/storage-pool/apps/gitea/data:/data
      - /mnt/storage-pool/apps/gitea/config:/etc/gitea
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.gitea.rule=Host(`git.starsystem.dev`)
      - traefik.http.services.gitea.loadbalancer.server.port=3000
    restart: always

  postgres:
    container_name: gitea-postgres
    image: postgres:17
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - /mnt/storage-pool/databases/postgresql/gitea:/var/lib/postgresql/data
    labels:
      - traefik.enable=false
    restart: always