networks:
  traefik_bridge:
    external: true

services:
  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin
    # Render group, needed for Jellyfin to use GPU
    group_add:
      - "107"
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
    env_file:
      - stack.env
    environment:
      TZ: Europe/London
    networks:
      - traefik_bridge
    volumes:
      - /mnt/storage-pool/apps/jellyfin/config:/config
      - /mnt/storage-pool/apps/jellyfin/cache:/cache
      - /mnt/storage-pool/media:/media
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.adguard.rule=Host(`media.starsystem.dev`)
      - traefik.http.services.adguard.loadbalancer.server.port=8096