networks:
  traefik_bridge:
    external: true

services:
  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin
    group_add:
      - "107" # render
      - "44" # video
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
    env_file:
      - stack.env
    networks:
      - traefik_bridge
    volumes:
      - /mnt/storage-pool/apps/jellyfin/config:/config
      - /mnt/storage-pool/apps/jellyfin/cache:/cache
      - /mnt/storage-pool/media:/media
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.jellyfin.rule=Host(`jellyfin.starsystem.dev`)
      - traefik.http.services.jellyfin.loadbalancer.server.port=8096