networks:
  default:
    name: lidarr_internal

  traefik_bridge:
    external: true

services:
  lidarr:
    container_name: lidarr
    image: lscr.io/linuxserver/lidarr:latest
    networks:
      - default
      - traefik_bridge
    volumes:
      - /mnt/storage-pool/apps/lidarr:/config
      - /mnt/storage-pool/media/music:/music
      - /mnt/storage-pool/media/downloads:/downloads
    labels:
      traefik.enable: true
      traefik.http.routers.lidarr.rule: Host(`lidarr.starsystem.dev`)
      traefik.http.routers.lidarr.middlewares: vpn-only@docker
      traefik.http.services.lidarr.loadbalancer.server.port: 8686
    restart: always

  exportarr:
    container_name: lidarr-exportarr
    image: ghcr.io/onedr0p/exportarr:v2.0
    networks:
      - default
    command: [ "lidarr" ]
    depends_on:
      - lidarr
    environment:
      PORT: "9707"
      URL: http://lidarr:8686
      APIKEY: ${API_KEY}
    labels:
      traefik.enable: false
    restart: always