networks:
  traefik_bridge:
    external: true

services:
  qbittorrent:
    container_name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent:latest
    ports:
      - "6881:6881"
      - "6881:6881/udp"
    environment:
      TORRENTING_PORT: "6881"
    networks:
      - traefik_bridge
    volumes:
      - /mnt/storage-pool/apps/qbittorrent:/config
      - /mnt/storage-pool/media/downloads:/downloads
    labels:
      - traefik.enable=true
      - traefik.http.routers.qbittorrent.rule=Host(`torrent.starsystem.dev`)
      - traefik.http.routers.qbittorrent.middlewares=vpn-only@docker
      - traefik.http.services.qbittorrent.loadbalancer.server.port=8080
    restart: always