networks:
  default:
    name: readarr_internal

  traefik_bridge:
    external: true

services:
  readarr:
    container_name: readarr
    image: lscr.io/linuxserver/readarr:develop
    user: 568:568
    networks:
      - default
      - traefik_bridge
    volumes:
      - /mnt/storage-pool/apps/readarr:/config
      - /mnt/storage-pool/media/books:/books
      - /mnt/storage-pool/media/downloads:/downloads
    labels:
      - traefik.enable=true
      - traefik.http.routers.readarr.rule=Host(`readarr.starsystem.dev`)
      - traefik.http.routers.readarr.middlewares=vpn-only@docker
      - traefik.http.services.readarr.loadbalancer.server.port=8787
    restart: always

  exportarr:
    container_name: readarr-exportarr
    image: ghcr.io/onedr0p/exportarr:v2.0
    networks:
      - default
    command: [ "readarr" ]
    depends_on:
      - readarr
    environment:
      PORT: "9707"
      URL: http://readarr:8787
      APIKEY: ${API_KEY}
    labels:
      - traefik.enable=false
    restart: always