networks:
  traefik_bridge:
    external: true

services:
  wg-easy:
    container_name: wg-easy
    image: ghcr.io/wg-easy/wg-easy
    ports:
      - 51820:51820/udp
    networks:
      - traefik_bridge
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    env_file:
      - stack.env
    environment:
      LANG: en
      PORT: "80"
      MAX_AGE: "0"
      WG_HOST: connect.starsystem.dev
      WG_PORT: "51820"
      WG_PERSISTENT_KEEPALIVE: "25"
      WG_DEFAULT_ADDRESS: 10.8.0.x
      WG_DEFAULT_DNS: "10.0.0.250"
      WG_ALLOWED_IPS: "0.0.0.0/0,::/0"
      WG_ENABLE_ONE_TIME_LINKS: "true"
      WG_ENABLE_EXPIRES_TIME: "true"
      WG_MTU: "1420"
      UI_TRAFFIC_STATS: "true"
      UI_CHART_TYPE: "1"
      UI_ENABLE_SORT_CLIENTS: "true"
      ENABLE_PROMETHEUS_METRICS: "true"
      PROMETHEUS_METRICS_PASSWORD: ${PROMETHEUS_METRICS_PASSWORD}
      PASSWORD_HASH: ${PASSWORD_HASH}
    volumes:
      - /mnt/storage-pool/apps/wgeasy:/etc/wireguard
    labels:
      - traefik.enable=true
      - traefik.http.routers.wg-easy.rule=Host(`vpn.starsystem.dev`)
      - traefik.http.services.wg-easy.loadbalancer.server.port=80
    restart: always