http:
  serversTransports:
    proxmox:
      insecureSkipVerify: true

  routers:
    clover-wings:
      entryPoints:
        - websecure
      rule: Host(`clover.games.starsystem.dev`)
      service: clover-wings

    truenas:
      entryPoints:
        - websecure
      rule: Host(`truenas.starsystem.dev`)
      service: truenas

    proxmox-web:
      entryPoints:
        - websecure
      rule: Host(`proxmox.starsystem.dev`)
      service: proxmox-web

    com-bluemap:
      entryPoints:
        - websecure
      rule: Host(`com.games.starsystem.dev`)
      service: com-bluemap

  services:
    clover-wings:
      loadBalancer:
        servers:
          - url: http://10.0.0.241:443

    truenas:
      loadBalancer:
        servers:
          - url: http://10.0.0.250:8080

    proxmox-web:
      loadBalancer:
        serversTransport: proxmox
        servers:
          - url: https://10.0.0.240:8006

    com-bluemap:
      loadBalancer:
        servers:
          - url: http://10.0.0.241:12000

# TODO: replace this with traefik kop