entryPoints:
  spice:
    address: ":3128"

  spice-tls:
    address: ":61000"

http:
  serversTransports:
    proxmox:
      insecureSkipVerify: true

  routers:
    clover-wings:
      entryPoints:
        - websecure
      rule: Host(`clover.games.starsystem.dev`)
      service: clover-wings

    truenas:
      entryPoints:
        - websecure
      rule: Host(`truenas.starsystem.dev`)
      service: truenas

    proxmox-web:
      entryPoints:
        - websecure
      rule: Host(`proxmox.starsystem.dev`)
      service: proxmox

    com-bluemap:
      entryPoints:
        - websecure
      rule: Host(`com.games.starsystem.dev`)
      service: com-bluemap

  services:
    clover-wings:
      loadBalancer:
        servers:
          - url: http://10.0.0.241:443

    truenas:
      loadBalancer:
        servers:
          - url: http://10.0.0.250:8080

    proxmox-web:
      loadBalancer:
        serversTransport: proxmox
        servers:
          - url: https://10.0.0.240:8006

    com-bluemap:
      loadBalancer:
        servers:
          - url: http://10.0.0.241:12000

tcp:
  routers:
    proxmox-spice:
      entryPoints:
        - spice
      rule: HostSNI(`*`)
      service: proxmox-spice

    proxmox-spice-tls:
      entryPoints:
        - spice-tls
      rule: HostSNI(`proxmox.starsystem.dev`)
      service: proxmox-spice-tls

  services:
    proxmox-spice:
      loadBalancer:
        servers:
          - address: 10.0.0.240:3128

    proxmox-spice-tls:
      loadBalancer:
        servers:
          - address: 10.0.0.240:61000

# TODO: replace this with traefik kop